<?php echo $this->doctype(); ?>

<html lang="UTF-8">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

        <?php echo $this->headTitle($this->layoutHelper()->getTabTitle())->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->partial('pedido/layout/css'); ?>


    </head>
    <body>

    <div class="pedidoBack">

        <div class="pedidoHead"></div>

        <div class="clearfix"></div>
        <div class="pedidoBody" >
            <?php echo $this->content; ?>
        </div>

        <div class="pedidoFooter"></div>
    </div>
    <?php echo $this->partial('pedido/layout/js'); ?>
    </body>
</html>
