

<p>Su pedido de Cinta fue cargado cargado con exito</p>



<ul>

    <li>
        <strong>Usuario:</strong> <?php echo $formularioCinta->getUsuario()->getUsername(); ?>
    </li>
    <li>
        <strong>Número de Pedido:</strong> #<?php echo $formularioCinta->getId(); ?>
    </li>

    <li>
        <strong>Color:</strong> <?php echo $formularioCinta->getColor(); ?>
        <span style="width: 30px; height: 10px; background-color: <?php echo $formularioCinta->getColor()->getHexa(); ?>">&nbsp;&nbsp;&nbsp;</span>
    </li>

    <li>
        <strong>Color Fondo:</strong>  <?php echo $formularioCinta->getColorFondo(); ?>
        <span style="width: 30px; height: 10px; background-color: <?php echo $formularioCinta->getColorFondo()->getHexa(); ?>">&nbsp;&nbsp;&nbsp;</span>
    </li>

    <li>
        <strong>Texto:</strong>  <?php echo $formularioCinta->getNombre(); ?>
    </li>

    <li>
        <strong>Opción:</strong>  <?php echo $formularioCinta->getOpcion(); ?>
    </li>


    <li>
        <strong>Dibujo:</strong><br>

        <?php if($formularioCinta->getDibujoPersonalizado()): ?>
            <img style="width: 50px" src="http://formularios.crearte.net.ar/media/dibujos-personalizados/<?php echo $formularioCinta->getDibujoPersonalizado(); ?>">
        <?php else: ?>
            <img style="width: 50px" src="http://formularios.crearte.net.ar/media/dibujos/<?php echo $formularioCinta->getDibujo()->getImg(); ?>">
        <?php endif; ?>


    </li>

</ul>


<h3>Preview</h3>

<div style="width: 500px; height: 100px">
    <table>
        <tr>
            <td style="width:100px;min-width:100px;">

                <?php if($formularioCinta->getDibujoPersonalizado()): ?>
                    <img style="width: 50px" src="http://formularios.crearte.net.ar/media/dibujos-personalizados/<?php echo $formularioCinta->getDibujoPersonalizado(); ?>">
                <?php else: ?>
                    <img style="width: 50px" src="http://formularios.crearte.net.ar/media/dibujos/<?php echo $formularioCinta->getDibujo()->getImg(); ?>">
                <?php endif; ?>
            </td>
            <td style="
                    min-width:400px;
                    width:400px;
                    text-align: center;
                    vertical-align: center;
                    font-size: 20px;
                    color: <?php echo $formularioCinta->getColor()->getHexa(); ?>;
                    background-color: <?php echo $formularioCinta->getColorFondo()->getHexa(); ?>;
                    "
            >
                <?php echo $formularioCinta->getNombre(); ?>
            </td>
        </tr>

    </table>
</div>
<br><br>
<p>Una vez terminado el trabajo le enviaremos un mail.</p>

<p>Saludos ATTE</p>

<strong>Grafica CR Print</strong><br>
<span>Tel 3969-7409</span><br>
<span>Whatsapp 11 6736-3333</span><br>
<span>Av. Juan B. Alberdi 1924</span><br>