<link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">
<div class="row">
    <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
        <div class="card">
            <div class="card-content">
                <div id="app" class="m5">
                    <cintasrevendedor :config='<?php echo json_encode($this->config); ?>'></cintasrevendedor>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal" tabindex="-100" role="dialog"
     id="mresultado"
     aria-labelledby="mresultado" data-keyword="true" data-backdrop="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <div id="resultado">

                </div>
            </div>
        </div>
    </div>
</div>


<?php
$this->headScript()
    ->appendFile('/shared/vuejs/vue.js')
    ->appendFile('/module/pedido/vue/preview.js?v=1', 'text/javascript')
    ->appendFile('/module/pedido/vue/opcion.js', 'text/javascript')
    ->appendFile('/module/pedido/vue/color.js', 'text/javascript')
    ->appendFile('/module/pedido/vue/dibujo.js', 'text/javascript')
    ->appendFile('/module/pedido/vue/cintasrevendedor.js?v=1', 'text/javascript')
    ->appendFile('/module/pedido/vue/app.js', 'text/javascript');

echo $this->headLink()
    ->appendStylesheet($this->basePath() . '/module/revendedor/custom.css');

?>

