



<div class="row">
    <div class="col-lg-3 col-md-4 col-xs-12 col-sm-6">
        <a href="/cr/formulario-cinta/grid">
            <div class="card card-chart" data-count="4">
                <div class="card-header" data-background-color="red" data-header-animation="true">
                    <i class="material-icons cubeIcon">reorder</i>
                </div>
                <div class="card-content">
                    <h4 class="card-title text-center">Formularios</h4>
                </div>
            </div>
        </a>
    </div>

    <div class="col-lg-3 col-md-4 col-xs-12 col-sm-6">
        <a href="/cr/dibujo/grid">
            <div class="card card-chart" data-count="4">
                <div class="card-header" data-background-color="green" data-header-animation="true">
                    <i class="material-icons cubeIcon">collections</i>
                </div>
                <div class="card-content">
                    <h4 class="card-title text-center">Dibujos</h4>
                </div>
            </div>
        </a>
    </div>

    <div class="col-lg-3 col-md-4 col-xs-12 col-sm-6">
        <a href="/cr/color/grid">
            <div class="card card-chart" data-count="4">
                <div class="card-header" data-background-color="green" data-header-animation="true">
                    <i class="material-icons cubeIcon">color_lens</i>
                </div>
                <div class="card-content">
                    <h4 class="card-title text-center">Colores</h4>
                </div>
            </div>
        </a>
    </div>

    <div class="col-lg-3 col-md-4 col-xs-12 col-sm-6">
        <a href="/cr/medida/grid">
            <div class="card card-chart" data-count="4">
                <div class="card-header" data-background-color="green" data-header-animation="true">
                    <i class="material-icons cubeIcon">format_size</i>
                </div>
                <div class="card-content">
                    <h4 class="card-title text-center">Medidas</h4>
                </div>
            </div>
        </a>
    </div>
</div>

<style>
    .cubeIcon {
        position: relative;
        text-align: center;
        width: 100%;
        font-size: 80px;
        margin-top: 15px;
        margin-bottom: 10px;
    }
</style>
